# Generated by Django 4.2.9 on 2024-01-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("controller_name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("api_key", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("carbon_dioxide", models.IntegerField()),
                ("voc_raw", models.FloatField()),
                ("nox_raw", models.FloatField()),
                ("voc_index", models.FloatField()),
                ("nox_index", models.FloatField()),
                ("sensor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.sensor")),
            ],
        ),
    ]
