# Generated by Django 4.2.7 on 2023-12-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("api_key", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("carbon_dioxide", models.IntegerField()),
                ("sensor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.sensor")),
            ],
        ),
    ]
