# Generated by Django 4.2.11 on 2024-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_sensorreading_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensorreading",
            name="nox_raw",
        ),
        migrations.RemoveField(
            model_name="sensorreading",
            name="voc_raw",
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="pm10",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="pm1_0",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="pm2_5",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="carbon_dioxide",
            field=models.FloatField(),
        ),
    ]
