# Generated by Django 4.2.11 on 2024-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_sensorreading_nox_raw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="pm10",
            field=models.FloatField(verbose_name="PM10"),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="pm1_0",
            field=models.FloatField(verbose_name="PM1.0"),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="pm2_5",
            field=models.FloatField(verbose_name="PM2.5"),
        ),
    ]
